config/routes.rb
Flashcard::Application.routes.draw do
  resources :words do 
    resources :mnemonics, :only => [:create, :index, :update, :show, :destroy]
  end
  
  
  match 'wordnik/definitions/:id' => 'wordnik#definitions'
  match 'wordnik/flashcard/:id' => 'wordnik#flashcard'
  match 'wordnik/example/:id' => 'wordnik#example'
  match 'wordnik/audio/:id' => 'wordnik#audio'
  
  match 'quiz/fill/:id' => 'quiz#fill'
  match 'quiz/result' => 'quiz#result'
  
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/facebook", :as => :signin
  match "/signout" => "sessions#destroy", :as => :signout
  
  match "/learn" => "hub#learn", :as => :learn
  match "/memorize" => "hub#memorize", :as => :memorize
  match "/quiz" => "hub#quiz", :as => :quiz
  
  root :to =>"hub#index"
  
  
  

end

app/controllers/hub_controller.rb
class HubController < ApplicationController
  before_filter :authenticate, :except => [:index]
  def index
    if signed_in?
      redirect_to learn_url
    else
      render :layout => false
    end
  end
  
  def learn
    @title = "TeachSavy.com - Flashcard"
    data = []
    
    current_user.lists.find_by_progress("incomplete").words.each do |word|
      data << word
    end
    
    @words = data.shuffle
    @user = current_user
  end
  
  def memorize
    @title = "TeachSavy.com - Flashcard"
    data = []
    
    current_user.lists.find_by_progress("incomplete").words.each do |word|
      data << word
    end
    
    @words = data.shuffle
    @user = current_user
  end
  
  def quiz
    @words = current_user.quizWordList
    word = @words.first
    assignment_words = current_user.words.where("word_id not in (?)", word).sample(2) << word
    @answers = Word.where("id not in (?)", assignment_words).sample(2).concat(assignment_words).shuffle!
    @sentence = Wordnik.sentence(word.name)
  end
end

app/helpers/hub_helper.rb
module HubHelper
end

app/views/hub/index.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">

  
    <title> Home</title>
    <link href="stylesheets/index/screen.css" media="screen" rel="stylesheet" type="text/css">
<link href="stylesheets/index/print.css" media="print" rel="stylesheet" type="text/css">
<!--[if lt IE 8]><link href="/stylesheets/blueprint/ie.css?1277496075" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
<link href="stylesheets/index/custom.css" media="screen" rel="stylesheet" type="text/css">
</head><body>

    <div class="container">
    <div id="header" class="round">
  <a href="#"><img alt="Sample App" class="round" src="stylesheets/index/logo.png"></a>
  <ul class="navigation round">
    <li><a href="#">Home</a></li>
    
    <li><a href="#help">Help</a></li>
    
    <li><a href="#signin">Sign in</a></li>
    
  </ul>
</div>


      <div id="content" class="round">
        
        
<h1>Flashcard testing</h1>

<p>
 Sample Demo/landing page.
</p>

<%= link_to "Sign in with Facebook", signin_path, {:class => "signup_button round"} %>



      </div>

    <div id="footer">
  <ul class="navigation round">
    <li><a href="#about">About</a></li>
    <li><a href="#contact">Contact</a></li>
    <li><a href="#">News</a></li>
  </ul>
</div>

    
    </div>

  </body></html>

app/views/hub/memorize.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "flashcard", "footer",  "mp3-player-button" %>
  <%= javascript_include_tag "jquery.keyNavi", "soundmanager2" %>
  
  <script type="text/javascript">
    
  var slideWidth = 650;
  var currentPosition = 0;
  var loadCount = 2; // preloaded 2 cards on first load.
  // dataSets of the words from a set; note they are randomized from the server. 
  var dataSet = <%= raw(@words.collect(&:name).inspect) %>; 
  var dataSetId = <%= raw(@words.collect(&:id).inspect) %>; 
  var numberOfSlides = <%= @words.size %>;
  
  var app = {
    /**
    * Binds your keyboard Left, Right, Up, Down.
    * Left and right binds move to the next flashcard in the sequence. 
    * Up and down toggles the hidden div to display the last selected word's definition. 
    */
    setupKeyboard: function(){
      $.keyNavi(function(){
        if(!$("#leftControl").is(":hidden"))
          $("#leftControl").trigger("click");
      }, function(){
        if(!$("#rightControl").is(":hidden"))
          $("#rightControl").trigger("click");
      }, function(){
        $('#footerSlideContent').slideToggle(true); 
      }, function(){
        $('#footerSlideContent').slideToggle(false);
      });
    },
    
    /**
    * Set up tabs to either hide or show thier respective <div> elements. 
    */ 
    setupTabs: function(){
      $(".tab_content").hide(); //Hide all content
    	$("ul.tabs li:first").addClass("active").show(); //Activate first tab
    	$(".tab_content:first").show(); //Show first tab content

    	//On Click Event
    	$("ul.tabs li").click(function() {

    		$("ul.tabs li").removeClass("active"); //Remove any "active" class
    		$(this).addClass("active"); //Add "active" class to selected tab
    		$(".tab_content").hide(); //Hide all tab content

    		var activeTab = $(this).find("a").attr("href"); //Find the href attribute value to identify the active tab + content
    		$(activeTab).fadeIn(); //Fade in the active ID content
    		return false;
    	});
    },
    
    /**
    * Ensure all flashcards are of the same size and width, flashcard are arranged 
    * in a horizontal manner and acts like a window frame exposing hidden cards. 
    */
    setupCards: function(){
      $.each(dataSet, function(i, word){
        var slideDiv = "<div class='slide'><div id=" + i + 
        " class='flashcard'><div class='card'><div id='word' class='word'>" + word + 
        "<a href='#' class='hidden' id='audiolink'></a>" +
        "</div><div id='definition' class='hidden'><ol class='def-list'></ol>" +
        "</div></div></div></div>";
        $('#slidesContainer').append(slideDiv);
      });
            
      // Should pre-load 2 before rendering and not use AJAX
      app.populateCard(0);
      app.getWordAudio(0);
      app.populateCard(1);

      // Remove scrollbar in JS
      $('#slidesContainer').css('overflow', 'hidden');

      var $cards = $('.slide');
      $cards.wrapAll('<div id="slideInner"></div>')
    	  .css({
          'float' : 'left',
          'width' : slideWidth
        });

      // Set #slideInner width equal to total width of all slides
      $('#slideInner').css('width', slideWidth * numberOfSlides);

      // Insert controls in the DOM
      $('#slideshow')
        .prepend('<span class="control" id="leftControl"></span>')
        .append('<span class="control" id="rightControl"></span>');

      // Hide left arrow control on first load
      this.manageControls(currentPosition);
    },
    
    /**
    * Determines the next position of the card and whether controls and text on the card 
    * should be shown. 
    * position: integer representation of the next index card. 
    */
    manageControls: function(position){
      // Hide left arrow if position is first slide
  	  if(position==0){ $('#leftControl').hide() } else{ $('#leftControl').show() }
  	  // Hide right arrow if position is last slide
      if(position==numberOfSlides-1){ $('#rightControl').hide() } else{ $('#rightControl').show() } 
    },
    
    /**
    * Populate card from the server via AJAX. Populated content becomes static, meaning each card
    * is only populated once via AJAX and stored on to HTML (until the page is refresehed).
    * index: integer representation of the index from array of words. (current position)
    */
    populateCard: function(index){
      $.ajax({
        dataType: 'json',
        url: "/wordnik/definitions/" + dataSet[index],
        success : function(result){
          var $container = $('#'+ index);
          var $content = $container.find('.card');
          var $ol = $content.find('.def-list');
          
          $.each(result, function(index, data){
            var $posDiv = $('<div class="pos" id="'+ data.partOfSpeech +'">&ndash;' + data.partOfSpeech + '</div>');
            if($ol.find('.pos[id="'+ data.partOfSpeech +'"]').length == 0) {
              $posDiv.appendTo($ol);
            }
            var $def = $('<li>' + data.text + '</li>');
            $def.appendTo($ol);
          });
        }
      });
    },

    /**
    * Set up "live" binds on all <li> elements in the list of selected-able Mnemonics from 
    * other users (from facebook). Selected elements are then inform to the server and set
    * as the current user's default mnemonic for this word.       
    */
    setupLiveBinds: function(){
      $('.slide .flashcard').live('click.flashcardToggle', function(){
        var $word = $(this).find('#word');
        var $definition = $(this).find('#definition');
        
        if($definition.hasClass('hidden')) {
          $definition.removeClass().addClass('definition');
          $word.removeClass().addClass('title');
          $(this).find('#audiolink').removeClass().addClass('sm2_button');
          $(this).find('#mute').show();
        }else{
          $definition.removeClass().addClass('hidden');
          $word.removeClass().addClass('word');
          $(this).find('#audiolink').removeClass().addClass('hidden');
          $(this).find('#mute').hide();
        }
        return false;
      });
      
      $('#audiolink').live('click.playAudio', function(){
        soundManager.play('word');
        return false;
      });
    },
    
    setupWordAudio: function(){
      soundManager.url = '/';
      soundManager.debugMode = false;
    },
    
    getWordAudio: function(index){
      soundManager.destroySound('word');
      $.ajax({
        dataType: 'text',
        url: "/wordnik/audio/" + dataSet[index],
        success : function(result){
          soundManager.onready(function() {
            var aSoundObject = soundManager.createSound({
             id:'word',
             url: result,
             onload: function(success){
               if(!success)
                  app.getWordAudio(index);
             }
            });
          });
        },
        error: function (){
          $img = $("<img>").attr('src', '/images/mute.png').attr('width', '22')
                  .attr('height', '22').css("display", "none").attr("id", "mute");
          $("#" + index).find("#audiolink").replaceWith($img);
        }
      });
    }
  };
  
  $(document).ready(function(){
    app.setupKeyboard();
    app.setupTabs();
    app.setupCards();
    app.setupLiveBinds();
    app.setupWordAudio();
    
    $('.control').bind('click', function(){
      // Cache all AJAX request; see populateCard for more info
      if(loadCount < numberOfSlides){
        app.populateCard(loadCount);
        loadCount++;
      }

      // Determine new position, whether to go right or left
  	  currentPosition = ($(this).attr('id')=='rightControl') ? currentPosition+1 : currentPosition-1;

      app.getWordAudio(currentPosition);
      $('.control').hide();
      $('#slideInner').animate({
        'marginLeft' : slideWidth*(-currentPosition)
      }, function(){
        // Hide / show controls
          app.manageControls(currentPosition);
      });
      
      return false;
    });  
  });
  </script>
<% end %>

<div class='container'>
  <br>
  <div style="width: 200px; height: 300px; float: left; background: lightBlue; z-index: 30; position: absolute;">
    <% if current_user %>
      Welcome <%= current_user.name %>!
      <%= link_to "Sign Out", signout_path %>
    <% end %>
    <ol>
      Word list
      <li>first</li>
    </ol>
  </div>
  <div id="slideshow">
    <div id="slidesContainer">
    </div>
  </div>  
</div>

app/views/hub/quiz.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    function getFillQuestion(wordIndex, $selector){
      $.ajax({
        dataType: 'html',
        url: "/quiz/fill/" + wordIndex,
        success : function(result){
          $selector.html(result);
        }
      });
    }
    
    function getResult(wordArray, answerArray, $selector){
      $.ajax({
        type: "POST",
        data: {"word_id": wordArray, "answers": answerArray},
        url: "/quiz/result",
        dataType: 'html',
        success : function(result){
          $selector.html(result);
        }
      });
    }
  
    $(function(){
      //Probably should save wordId in a session states in rails instead.
      var wordId = <%= raw(@words.collect(&:id).inspect) %>; 
      var answer = [];
      var index = 0;
      var $unique = $('input.unique');
      $unique.click(function() {
         $unique.filter(':checked').not(this).removeAttr('checked');
      });

      $('#Next').live("click", function(){
        if($("input.unique:checked").length){
          answer.push($('input.unique:checked').val());
        }else{
          answer.push('');
        }
    
        index++;
        if(index < wordId.length){
          getFillQuestion(wordId[index], $("#quiz"));
        }else{
          getResult(wordId, answer, $("#quiz"));
        }
      });
    });
  </script>
  <style>
    .inner {
      width: 50%;
      margin: auto;
    }
    
    #controls{
      float: right;
    }
  </style>
<% end %>
<div class='container'>
  <br>
  <div id="title" class="inner">
    <h2>Quiz yourself</h3>
  </div>
  <div id="quiz" class="inner">
    <div id="question"> 
      <p>
        <%= @sentence %>
      </p>
    </div>
    <hr>  
    <div id="answer" class="inner">
      <% @answers.each do |answer|%>
      <input type='checkbox' value='<%= answer.id %>' class='unique'/><%= answer.name %><br/>
      <% end %>
    </div>
    <div id="controls">
      <input type='button' value='Submit' id="Next"/>
    </div>
  </div>
</div>